baseURL = "http://localhost:1313/PTEROSOR/"
#baseURL = "https://lcpq.github.io/PTEROSOR/"
canonifyurls  = true
languageCode = "en-us"
DefaultContentLanguage = "en"
theme = "beautifulhugo"
title = "PT-symmetric electronic structure theory"
[Params]
  hometitle = "ERC PTEROSOR"
  logo="img/PTEROSOR.png"
#  subtitle = ""
[[Params.bigimg]]
  src = "img/banner.png"
  desc = "New methodologies for excited states"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[Author]
  name = "Titou Loos"
  email = "loos@irsamc.ups-tlse.fr"
  github = "LCPQ"
  twitter = "PTEROSOR"
  youtube = "channel/UCPUtUMqEM3K5sYcMJGTd_Bg"

[[menu.main]]
    name = "Home"
    url = ""
    weight = 1

[[menu.main]]
    name = "People"
    url = "people"
    weight = 2

[[menu.main]]
    name = "Software"
    url = "software"
    weight = 3

[[menu.main]]
    name = "Publications"
    url = "publications"
    weight = 4

[[menu.main]]
    identifier = "external"
    name = "External links"
    weight = 7

[[menu.main]]
    parent="external"
    name = "Laboratoire de Chimie et Physique Quantiques"
    url = "http://www.lcpq.ups-tlse.fr"
    weight = 1

[[menu.main]]
    parent="external"
    name = "Quantum Package"
    url = "https://quantumpackage.github.io/qp2"
    weight = 2

[[menu.main]]
    parent="external"
    name = "European Research Council"
    url = "https://erc.europa.eu"
    weight = 3

[[menu.main]]
    parent="external"
    name = "arXiv"
    url = "https://arxiv.org"
    weight = 4

[[menu.main]]
    parent="external"
    name = "HAL"
    url = "https://hal.archives-ouvertes.fr"
    weight = 5


